# -*- coding: utf-8 -*-
"""Copy of Nehemiah_Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rTjuFn2aBeN-MfU6zl66X6nbfUxurBWu
"""

# INFO 450_HW

                      # December 08, 2025

"""1: Load and Explore Data"""

# Import libraries
import time
import urllib.request
import pandas as pd

# URL to download the dataset
url = "https://storage.googleapis.com/info_450/IndividualAssistanceHousingRegistrantsLargeDisasters%20(1).csv"
filename = "fema_disaster_data.csv"

# Measure the time taken to download the file
print(f"Downloading {filename}...")
start = time.time()
urllib.request.urlretrieve(url, filename)
print(f"Done in {time.time() - start:.2f} seconds.")

# Load the dataset into a DataFrame
df = pd.read_csv(filename, low_memory=False)

# Display the first few rows to ensure it's loaded properly
df.head()

"""N/A

2: Select Relevant Columns and Handle Missing Values
"""

cols = [
    "disasterNumber",
    "damagedCity",
    "damagedStateAbbreviation",
    "residenceType",
    "grossIncome",
    "tsaEligible",
    "repairAmount",
    "destroyed",
    "waterLevel",
    "specialNeeds"
]

df = df[cols].copy()

# Basic cleaning
str_cols = ["damagedCity", "damagedStateAbbreviation", "residenceType", "grossIncome"]
for c in str_cols:
    df[c] = df[c].astype(str).str.strip()

# Handle missing values
df["damagedCity"] = df["damagedCity"].replace(["", "nan", "NaN", "None"], "Unknown")
df["residenceType"] = df["residenceType"].replace(["", "nan", "NaN", "None"], "Unknown")
df["grossIncome"] = df["grossIncome"].replace(["", "nan", "NaN", "None"], "Unknown")

df["tsaEligible"] = pd.to_numeric(df["tsaEligible"], errors="coerce")
df = df[df["tsaEligible"].isin([0, 1])]

df["repairAmount"] = pd.to_numeric(df["repairAmount"], errors="coerce")
df["repairAmount"] = df["repairAmount"].fillna(0)  # Assume missing repair amounts are 0

df["waterLevel"] = pd.to_numeric(df["waterLevel"], errors="coerce")
df["waterLevel"] = df["waterLevel"].fillna(0)  # Assume missing water levels are 0

# Check for remaining missing values
print("Remaining missing values:")
print(df.isna().sum())

"""N/A

3: EDA
"""

# 3: EDA – TSA by residence type and state

ct_res_state = pd.crosstab(
    [df["damagedStateAbbreviation"], df["residenceType"]],
    df["tsaEligible"],
    normalize="index"
)

ct_res_state.rename(columns={0: "Not_TSA_Eligible", 1: "TSA_Eligible"}, inplace=True)
ct_res_state.head(10)

"""N/A

4: Average Repair Amount by State
"""

avg_repair_by_state = (
    df.groupby("damagedStateAbbreviation", as_index=False)["repairAmount"]
      .mean()
      .rename(columns={"repairAmount": "avgRepairAmount"})
      .sort_values("avgRepairAmount", ascending=False)
)

avg_repair_by_state.head(10)

"""N/A

5: Part.1 Histogram
"""

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10,5))
sns.histplot(df["repairAmount"].dropna(), bins=40, kde=False)
plt.xlabel("Repair Amount (USD)")
plt.ylabel("Count")
plt.title("Distribution of Repair Amount")
plt.tight_layout()
plt.show()

"""N/A

5: Part.2 Boxplot Repair by Residence Type
"""

plt.figure(figsize=(12,6))
sns.boxplot(data=df, x="residenceType", y="repairAmount")
plt.xticks(rotation=45)
plt.xlabel("Residence Type")
plt.ylabel("Repair Amount (USD)")
plt.title("Repair Amount by Residence Type")
plt.tight_layout()
plt.show()

"""N/A

5: Part.3 Boxplot Repair Amount by TSA
"""

plt.figure(figsize=(10,5))
sns.boxplot(data=df, x="tsaEligible", y="repairAmount")
plt.xlabel("TSA Eligible (1 = Yes, 0 = No)")
plt.ylabel("Repair Amount (USD)")
plt.title("Repair Amount by TSA Eligibility")
plt.tight_layout()
plt.show()

"""N/A

Load Data Again
"""

import pandas as pd

# Load the dataset (ensure the file path is correct)
df = pd.read_csv("fema_disaster_data.csv", low_memory=False)

# Display the first few rows of the dataframe to verify
df.head()

"""N/A

5: Part.4 TSA Eligibility Rate by Gross Income
"""

import plotly.express as px

# Ensure that grossIncome is numeric, convert invalid parsing to NaN
df["grossIncome"] = pd.to_numeric(df["grossIncome"], errors="coerce")

# Handle missing values in grossIncome (you can choose to fill or drop)
df["grossIncome"] = df["grossIncome"].fillna(0)  # Replace missing values with 0 (or use another strategy)

# Compute TSA eligibility rate by grossIncome category
tsa_by_income = (
    df.groupby("grossIncome")["tsaEligible"]
    .mean()
    .reset_index(name="tsaRate")
    .sort_values("tsaRate", ascending=False)  # Sort by eligibility rate
)

# Plot TSA eligibility rate by gross income category using Plotly
fig_income = px.bar(tsa_by_income, x="grossIncome", y="tsaRate", title="TSA Eligibility Rate by Gross Income")
fig_income.update_layout(
    xaxis_title="Gross Income Category",
    yaxis_title="TSA Eligibility Rate"
)
fig_income.show()  # Display the interactive bar plot

"""N/A

(Part II- Inferential Statistics) 5: Helper Function for 95% CI of Mean
"""

import numpy as np
import scipy.stats as stats

# Helper function for 95% Confidence Interval of Mean
def mean_confidence_interval(data, confidence=0.95):
    """
    Calculate the confidence interval for the mean of a dataset.

    Parameters:
    - data: The data (Series or array-like) for which the confidence interval is calculated.
    - confidence: The confidence level, default is 95%.

    Returns:
    - mean: The sample mean.
    - lower: The lower bound of the confidence interval.
    - upper: The upper bound of the confidence interval.
    - n: The sample size.
    """
    data = np.array(data.dropna())  # Drop missing values
    if len(data) == 0:
        return np.nan, np.nan, np.nan, 0  # Return NaN if the data is empty

    n = len(data)  # Sample size
    mean = np.mean(data)  # Mean of the sample
    sem = stats.sem(data)  # Standard error of the mean
    h = sem * stats.t.ppf((1 + confidence) / 2, n - 1)  # Margin of error
    return mean, mean - h, mean + h, n  # Return the mean, lower bound, upper bound, and sample size

"""N/A

5: Part.2 CI TSA-Eligible vs Not-Eligible
"""

# Extract repair amounts for TSA-Eligible and Non-TSA-Eligible households
tsa = df[df["tsaEligible"] == 1]["repairAmount"].dropna()  # TSA-Eligible
not_tsa = df[df["tsaEligible"] == 0]["repairAmount"].dropna()  # Non-TSA-Eligible

# Calculate confidence intervals for TSA-Eligible households
mean_tsa, lower_tsa, upper_tsa, n_tsa = mean_confidence_interval(tsa)
print("TSA-Eligible households:")
print(f"  n = {n_tsa}")
print(f"  Mean repairAmount = {mean_tsa:,.2f}")
print(f"  95% CI = [{lower_tsa:,.2f}, {upper_tsa:,.2f}]")

# Calculate confidence intervals for Non-TSA-Eligible households
mean_not, lower_not, upper_not, n_not = mean_confidence_interval(not_tsa)
print("\nNon-TSA-Eligible households:")
print(f"  n = {n_not}")
print(f"  Mean repairAmount = {mean_not:,.2f}")
print(f"  95% CI = [{lower_not:,.2f}, {upper_not:,.2f}]")

"""N/A

5: Part.3 Two- Sample T-Test
"""

# Two-sample t-test (Welch’s t-test) to compare TSA-Eligible vs Non-TSA-Eligible households
tstat, pval = stats.ttest_ind(tsa, not_tsa, equal_var=False)  # Welch's t-test assumes unequal variance
print(f"\nTwo-sample t-test (Welch): t = {tstat:.3f}, p = {pval:.4g}")

"""N/A

5: Part.4 CI Repair Amount by State
"""

# Comparison between two states (e.g., Texas and Louisiana)
state1 = "TX"
state2 = "LA"

# Extract repair amounts for Texas and Louisiana
s1 = df[df["damagedStateAbbreviation"] == state1]["repairAmount"].dropna()
s2 = df[df["damagedStateAbbreviation"] == state2]["repairAmount"].dropna()

# Calculate confidence intervals for each state
mean1, low1, up1, n1 = mean_confidence_interval(s1)
mean2, low2, up2, n2 = mean_confidence_interval(s2)

# Print results for both states
print(f"{state1}: n={n1}, mean={mean1:,.2f}, 95% CI=[{low1:,.2f}, {up1:,.2f}]")
print(f"{state2}: n={n2}, mean={mean2:,.2f}, 95% CI=[{low2:,.2f}, {up2:,.2f}]")

# Perform a two-sample t-test (Welch’s) for the two states
tstat_states, pval_states = stats.ttest_ind(s1, s2, equal_var=False)
print(f"\nTwo-sample t-test: t={tstat_states:.3f}, p={pval_states:.4g}")

"""N/A

6: (Part III- Predictive Modeling)
"""

import pandas as pd

# Load the dataset
df = pd.read_csv("fema_disaster_data.csv")  # Make sure this file exists in the working directory

# Alternatively, if the file path is different, use the full path
# df = pd.read_csv("/path/to/fema_disaster_data.csv")

try:
    # Print the first few rows of the dataframe
    print(df.head())

    # Print the data types of each column
    print(df.dtypes)

except Exception as e:
    # If an error occurs, print the error message
    print(f"Error: {e}")

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Prepare the dataset for modeling
model_df = df.copy()
model_df = model_df.dropna(subset=["repairAmount"])  # Drop rows with missing repairAmount

# Select features for modeling
features = [
    "repairAmount",
    "grossIncome",
    "destroyed",
    "waterLevel",
    "residenceType",
    "damagedStateAbbreviation",
    "specialNeeds"
]

# Filter data for features and the target variable (tsaEligible)
model_df = model_df[features + ["tsaEligible"]].copy()

# Fill remaining missing values for features (you can fill or drop based on your strategy)
model_df["waterLevel"] = model_df["waterLevel"].fillna(0)
model_df["destroyed"] = model_df["destroyed"].astype("Int64").fillna(0)
model_df["specialNeeds"] = model_df["specialNeeds"].astype("Int64").fillna(0)

# Handle categorical features by filling with 'Unknown'
for col in ["grossIncome", "residenceType", "damagedStateAbbreviation"]:
    model_df[col] = model_df[col].fillna("Unknown")

# Split the data into features (X) and target (y)
X = model_df.drop("tsaEligible", axis=1)
y = model_df["tsaEligible"]

"""N/A"""

# Import necessary libraries
import pandas as pd

# Load the dataset (ensure the file path is correct)
df = pd.read_csv("fema_disaster_data.csv")  # Ensure the correct path to the CSV file

# Display the first few rows of the dataframe to verify it has been loaded correctly
df.head()

"""6: Part.2 Encode Categorical Features"""

# Load the dataset (make sure the file path is correct)
df = pd.read_csv("fema_disaster_data.csv")

# Ensure categorical columns are treated as strings and handle missing values
df["grossIncome"] = df["grossIncome"].astype(str).fillna("Unknown")  # Convert to string and fill missing values
df["residenceType"] = df["residenceType"].astype(str).fillna("Unknown")
df["damagedStateAbbreviation"] = df["damagedStateAbbreviation"].astype(str).fillna("Unknown")

# Create the model_df (it should already be defined or created from the raw data)
model_df = df.copy()  # Make sure model_df exists

# Select features for modeling (excluding target variable 'tsaEligible')
X = model_df.drop("tsaEligible", axis=1)  # Features (excluding target column)

# One-hot encode the categorical variables using pd.get_dummies
X_encoded = pd.get_dummies(
    X,
    columns=["grossIncome", "residenceType", "damagedStateAbbreviation"],  # List the categorical columns to encode
    drop_first=True  # Drop the first category to avoid multicollinearity
)

# Check the shape of the encoded dataset
print(X_encoded.shape)  # This will display the number of rows and columns after encoding

# Check the first few rows of the encoded dataset
print(X_encoded.head())

"""N/A

Train Random Forest
"""

# Step 1: Select the target variable 'tsaEligible' and features 'X'
y = model_df["tsaEligible"]  # Target variable (TSA eligibility)
X = X_encoded  # Features (after encoding)

# Step 2: Split the data into training and testing sets (70% training, 30% testing)
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.3,  # 30% for testing, 70% for training
    random_state=42,  # For reproducibility
    stratify=y  # Ensures balanced distribution of classes (TSA eligible vs not)
)

# Step 3: Train the Decision Tree Classifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, confusion_matrix, classification_report

dt_clf = DecisionTreeClassifier(random_state=42)
dt_clf.fit(X_train, y_train)

# Step 4: Evaluate the Decision Tree Model
y_pred_dt = dt_clf.predict(X_test)

print("Decision Tree Classifier Performance")
print(f"Accuracy: {accuracy_score(y_test, y_pred_dt):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_dt):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_dt):.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_dt))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_dt))

# Step 5: Train the Random Forest Classifier
from sklearn.ensemble import RandomForestClassifier

rf_clf = RandomForestClassifier(random_state=42)
rf_clf.fit(X_train, y_train)

# Step 6: Evaluate the Random Forest Model
y_pred_rf = rf_clf.predict(X_test)

print("\nRandom Forest Classifier Performance")
print(f"Accuracy: {accuracy_score(y_test, y_pred_rf):.4f}")
print(f"Precision: {precision_score(y_test, y_pred_rf):.4f}")
print(f"Recall: {recall_score(y_test, y_pred_rf):.4f}")
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_rf))
print("\nClassification Report:")
print(classification_report(y_test, y_pred_rf))

"""N/A

Part 4: Streamlit Visual and Dashboard
"""

# We'll use a smaller subset for Streamlit if needed
streamlit_df = df_sample.copy()
streamlit_df.to_csv("fema_streamlit_data.csv", index=False)

"""N/A

Part IV - Streamlit App
"""

import streamlit as st
import pandas as pd
import plotly.express as px

st.set_page_config(page_title="FEMA Disaster Relief Dashboard", layout="wide")

st.title("FEMA Disaster Relief Dashboard")
st.write("Authors: Your Name")

# Load and clean the data
df = pd.read_csv("IndividualAssistanceHousingRegistrantsLargeDisasters (2).csv")
df["repairAmount"] = pd.to_numeric(df["repairAmount"], errors="coerce")
df["tsaEligible"] = pd.to_numeric(df["tsaEligible"], errors="coerce")

# Sidebar filters
states = ["All"] + sorted(df["damagedStateAbbreviation"].dropna().unique().tolist())
selected_state = st.sidebar.selectbox("Filter by State/Territory", states)

filtered_df = df.copy()
if selected_state != "All":
    filtered_df = filtered_df[filtered_df["damagedStateAbbreviation"] == selected_state]

# Plotting histogram
fig_hist = px.histogram(filtered_df, x="repairAmount", nbins=30, title="Distribution of Repair Amounts")
fig_hist.update_layout(xaxis_title="Repair Amount (USD)", yaxis_title="Count")
st.plotly_chart(fig_hist)

# Plotting boxplot for TSA eligibility
fig_box = px.box(filtered_df, x="tsaEligible", y="repairAmount", title="Repair Amount by TSA Eligibility")
fig_box.update_layout(xaxis_title="TSA Eligible (1 = Yes, 0 = No)", yaxis_title="Repair Amount (USD)")
st.plotly_chart(fig_box)